
const $=s=>document.querySelector(s);let sessionId=null,lastDiag=null;
const fields=[["situation","Situation"],["facts","Faits"],["observations","Observations"],["interpretations","Interprétations"],["hypotheses","Hypothèses"],["tensions","Tensions"],["unknowns","Ce qui reste à éclaircir"],["learnings","Apprentissages"],["directions","Directions"],["next_action","Prochaine action"]];
async function createSession(){const r=await fetch("/api/session",{method:"POST"});const s=await r.json();sessionId=s.id;localStorage.setItem("boussole_session",sessionId);renderState(s.state)}
async function load(){sessionId=localStorage.getItem("boussole_session");if(!sessionId)return createSession();const r=await fetch("/api/session/"+sessionId);if(!r.ok)return createSession();const s=await r.json();$("#messages").innerHTML="";if(!s.messages.length)add("assistant","Qu’est-ce qui t’amène ? Raconte-moi simplement ce qui se passe, même si c’est confus.");s.messages.forEach(m=>{add(m.role,m.text);if(m.diagnostic)lastDiag=m.diagnostic});renderState(s.state);renderDiag()}
function add(role,text){const a=document.createElement("article");a.className=role==="user"?"user":"assistant";const p=document.createElement("p");p.textContent=text;a.append(p);$("#messages").append(a);a.scrollIntoView({behavior:"smooth",block:"end"})}
function renderState(s){$("#phase").textContent=({brouillard:"Brouillard",clarte:"Clarté",experience:"Expérience",apprentissage:"Apprentissage",direction:"Direction"})[s.phase]||s.phase;const m=$("#map");m.innerHTML="";for(const [k,label] of fields){let v=s[k];if(Array.isArray(v))v=v.join(" · ");if(v){const d=document.createElement("div");d.className="mapitem";const b=document.createElement("b");b.textContent=label;const p=document.createElement("div");p.textContent=v;d.append(b,p);m.append(d)}}if(!m.children.length)m.innerHTML='<p class="muted">La carte se construira à partir de ce qui est réellement établi.</p>';const box=$("#experimentBox");if(s.pending_experiment){box.classList.remove("hidden");$("#experiment").textContent=JSON.stringify(s.pending_experiment,null,2)}else box.classList.add("hidden")}
function renderDiag(){if(lastDiag)$("#diagnostic").textContent=JSON.stringify(lastDiag,null,2)}
$("#form").addEventListener("submit",async e=>{e.preventDefault();const input=$("#input"),text=input.value.trim();if(!text)return;add("user",text);input.value="";input.disabled=true;$("#status").textContent="Boussole réfléchit à ce qui est réellement utile…";try{const r=await fetch(`/api/session/${sessionId}/message`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:text})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Erreur");add("assistant",d.message);lastDiag=d.diagnostic;renderDiag();renderState(d.state)}catch(err){add("assistant","Je n’ai pas pu répondre : "+err.message)}finally{input.disabled=false;input.focus();$("#status").textContent=""}});
$("#diagBtn").onclick=()=>{$("#diagnosticBox").classList.toggle("hidden");renderDiag()};
$("#newBtn").onclick=async()=>{if(sessionId)await fetch("/api/session/"+sessionId,{method:"DELETE"});localStorage.removeItem("boussole_session");$("#messages").innerHTML="";add("assistant","Qu’est-ce qui t’amène ? Raconte-moi simplement ce qui se passe, même si c’est confus.");lastDiag=null;await createSession()};
load();
